### ISSUE TITLE
United Kingdom

### ISSUE THREAD

**Issue by omsrivastava** [LucianoGanga/country-codes-list#10]
The country name should be changed to **United Kingdom** from **Great Britain** in `countryNameEn`. It's known as the **United Kingdom** more than **Great Britain**. The `countryNameLocal` can be **Great Britain**.

**Comment by LucianoGanga** [comment]
Done @omsrivastava ! Available at the version 1.6.3. Thank you for reporting this!

Also, thanks to @LucianoPaci who fixed this and sent the PR. 

Cheers!
Lucho
