### ISSUE TITLE
Missing countryCallingCode for some countries

### ISSUE THREAD

**Issue by laxu** [LucianoGanga/country-codes-list#12]
At least these countries seem to be missing `countryCallingCode`:

- Antarctica +672
- Bouvet Island +47
- Cabo Verde +238
- Cote d'Ivoire +225
- Laos +856
- Macao +853
- Syria +963
- Timor-Leste +670
- Western Sahara +212

Can you please add these? Country calling codes from quick googling.

**Comment by LucianoPaci** [comment]
Done! Thanks for the feedback!
