### ISSUE TITLE
Missing country codes (ISO 3166 COUNTRY CODES)

### ISSUE THREAD

**Issue by abdes** [LucianoGanga/country-codes-list#13]
From https://www.iso.org/iso-3166-country-codes.html, the following countries (yes they have registered codes, flags, etc... :-)) are missing:

- https://www.iso.org/obp/ui/#iso:code:3166:BS
- https://www.iso.org/obp/ui/#iso:code:3166:CC
- https://www.iso.org/obp/ui/#iso:code:3166:CD (the Democratic Republic of the Congo, this one is even a huge country :-) )
- https://www.iso.org/obp/ui/#iso:code:3166:CF
- https://www.iso.org/obp/ui/#iso:code:3166:CK
- https://www.iso.org/obp/ui/#iso:code:3166:FK
- https://www.iso.org/obp/ui/#iso:code:3166:FO
- https://www.iso.org/obp/ui/#iso:code:3166:HM
- https://www.iso.org/obp/ui/#iso:code:3166:IO
- https://www.iso.org/obp/ui/#iso:code:3166:KM
- https://www.iso.org/obp/ui/#iso:code:3166:KY
- https://www.iso.org/obp/ui/#iso:code:3166:MH
- https://www.iso.org/obp/ui/#iso:code:3166:MP
- https://www.iso.org/obp/ui/#iso:code:3166:TC
- https://www.iso.org/obp/ui/#iso:code:3166:TF
- https://www.iso.org/obp/ui/#iso:code:3166:UM
- https://www.iso.org/obp/ui/#iso:code:3166:VA

**Comment by laxu** [comment]
@LucianoPaci could you fix this one and after that do a new release on NPM with the fixes from https://github.com/LucianoGanga/country-codes-list/issues/12 ?
