### ISSUE TITLE
Are TypeScript typings available for this package?

### ISSUE THREAD

**Issue by jgb-solutions** [LucianoGanga/country-codes-list#19]
I started using this package and it doesn't have typings available which is annoying. If there are no typings available yet, i'll work on providing them for it. Just let me know.

**Comment by jpike88** [comment]
there aren't any available

**Comment by jgb-solutions** [comment]
ok. I'll find some time to make a pull request if you don't mind.

**Comment by jakeisnt** [comment]
Hey! I just added some rudimentary types and opened a PR here: https://github.com/LucianoGanga/country-codes-list/pull/21

Feel free to pull in my `.d.ts` file locally (as `country-codes-list.d.ts`) if you'd like to use it.

**Comment by LucianoPaci** [comment]
Hi Everyone! Thanks for your help!
I just merged PR #21 

Sorry for the delay. I will close this!
