### ISSUE TITLE
customList error issue by import

### ISSUE THREAD

**Issue by Lassin93** [LucianoGanga/country-codes-list#2]
Issue happen in import.
index.js:70 Uncaught (in promise) ReferenceError: value is not defined

Index.js
value = supplant(label, countryData);
Should be 
const value = supplant(label, countryData);

missing define value.

**Comment by LucianoGanga** [comment]
Hello @Lassin93 !! Thanks for the comment! And sorry for the late reply :( 

I fixed it in version 1.2.1, I hope you can use it :) 

Cheers, 
Luciano
