### ISSUE TITLE
publish newest version to npm?

### ISSUE THREAD

**Issue by flodev** [LucianoGanga/country-codes-list#23]
hi,
could you please publish the newest version 1.6.10 (which includes the types) to npm?
thanks in advance and regards.

**Comment by Jackman3005** [comment]
yes please! :)

**Comment by bsobbe** [comment]
yes please indeed!

**Comment by gewisser** [comment]
push someone a new version in npm please. I don't want to fork

**Comment by gewisser** [comment]
as a temporary solution:

```json
"country-codes-list": "github:LucianoGanga/country-codes-list#master",
```

**Comment by LucianoPaci** [comment]
Hi guys!

Sorry about the delay! I've pushed version 1.6.10 to npm!

**Comment by bsobbe** [comment]
@LucianoPaci Much appreciated.
