### ISSUE TITLE
Wrong return type of customArray?

### ISSUE THREAD

**Issue by scheidtdav** [LucianoGanga/country-codes-list#25]
I am using this awesome library with Typescript and came across `customArray`.
Its just what I wanted, but it seems that the return type is `string[]`.
Shouldn't it be something similar to `{value: string, name: string}[]`?

**Comment by paranicistefan1** [comment]
I'm having the same problem over here

**Comment by scheidtdav** [comment]
Closed #30 in favor of #31 which includes a more accurate implementation of types.

**Comment by LucianoPaci** [comment]
Hi everyone! Thanks for contributing. This was fixed on v1.6.11
