### ISSUE TITLE
Typescript index Incorrect computed property name type

### ISSUE THREAD

**Issue by steinsroka** [LucianoGanga/country-codes-list#33]
Hello,

The computed property name type in the customList function might incorrect. Currently, the code attempts to use CountryProperty as a computed property name, but TypeScript throws an error because CountryProperty is not a literal type or a unique symbol type.

The corrected code can be

index.d.ts:60
```
export function customList(
  key?: CountryProperty,
  label?: string,
  settings?: CustomArraySettings,
): { [K in CountryProperty]: string };
```
or
```
export function customList(
  key?: CountryProperty,
  label?: string,
  settings?: CustomArraySettings,
): { [key: string]: string };

```

**Comment by LucianoPaci** [comment]
Thanks! This was fixed on v1.6.11
