### ISSUE TITLE
How do I filter the country list down?

### ISSUE THREAD

**Issue by MichaelLiss** [LucianoGanga/country-codes-list#4]
Hi,

I am new to node js programming and am trying to use your object:

        var country = 'US';

    const myCountryCodesObject = countryCodes.customList('countryCode', '{countryCode} +{countryCallingCode}');
        var indx = myCountryCodesObject.indexOf(country);
        console.log('index ' + indx);

I assume that customList returns a list... and I could do an indexOf that list... but it's not working... 

Is there another way that I can get JUST the country code information for ONLY the country I am interested in ?

**Comment by Rincorpes** [comment]
@MichaelLiss Sure. You can use the `findOne()` method to that matter.

    const countryCodes = require('country-codes-list')

    // Find a country by a property and return the first match as an object
    console.log(countryCodes.findOne('countryCode', 'US') )

This will be the output

```
{
  countryNameEn: 'United States of America',
  countryNameLocal: 'United States of America',
  countryCode: 'US',
  currencyCode: 'USD',
  currencyNameEn: 'United States dollar',
  tinType: '',
  tinName: '',
  officialLanguageCode: 'en',
  officialLanguageNameEn: 'English',
  officialLanguageNameLocal: 'English',
  countryCallingCode: '1',
  region: 'North America',
  flag: '🇺🇸'
}
```

**Comment by MichaelLiss** [comment]
AWESOME !  Thank you
